import type { MetadataRoute } from "next";
import { services } from "@/data/services";
import { suburbs } from "@/data/suburbs";
import {
  indexableBlogPosts,
  categoryMap,
  getPostsByCategory,
} from "@/data/blog-posts";
import { SITE_URL, LEGAL_DATES } from "@/lib/site";

export const revalidate = 3600;

/* ---------------------------------------------------------------------------
 * Sitemap index IDs — each produces a separate XML file so crawlers and
 * Google Search Console can track indexing per content type, just like
 * Yoast's page-sitemap / blog-sitemap split.
 *
 *   /sitemap.xml        → sitemap index (auto-generated by Next.js)
 *   /sitemap/0.xml      → static pages + service pages
 *   /sitemap/1.xml      → location (suburb) pages
 *   /sitemap/2.xml      → blog posts + category pages
 * -------------------------------------------------------------------------*/
const SITEMAP_PAGES = 0;
const SITEMAP_LOCATIONS = 1;
const SITEMAP_BLOG = 2;

export async function generateSitemaps() {
  return [
    { id: SITEMAP_PAGES },
    { id: SITEMAP_LOCATIONS },
    { id: SITEMAP_BLOG },
  ];
}

/* ---------------------------------------------------------------------------
 * Image constant — only the hero image is relevant for Google Image search.
 * The logo is decorative and adds no crawl value.
 * -------------------------------------------------------------------------*/
const HERO_IMAGE = [`${SITE_URL}/images/tow-truck-hero.webp`];

/* ---------------------------------------------------------------------------
 * Date helpers — honest lastModified dates build crawler trust.  Using
 * "today" for pages that haven't changed erodes crawl budget over time.
 * -------------------------------------------------------------------------*/

/** Resolve a "Month YYYY" string (e.g. "April 2026") to an ISO date. */
function monthYearToISO(label: string): string {
  const d = new Date(`1 ${label}`);
  return d.toISOString().split("T")[0];
}

/** Pick a changeFrequency hint based on content age. */
function changeFreqByAge(
  isoDate: string,
): "daily" | "weekly" | "monthly" | "yearly" {
  const ageMs = Date.now() - new Date(isoDate).getTime();
  const ageDays = ageMs / 86_400_000;
  if (ageDays < 14) return "weekly";
  if (ageDays < 180) return "monthly";
  return "yearly";
}

/** The date the current content was deployed / last structurally changed. */
const CONTENT_DEPLOY_DATE = "2026-04-15";

/* -----------------------------------------------------------------------
 * Primary service slugs — money pages get the highest non-homepage priority
 * ---------------------------------------------------------------------*/
const PRIMARY_SERVICE_SLUGS = new Set([
  "cash-for-cars-brisbane",
  "car-removal-brisbane",
  "sell-my-car-brisbane",
]);

/* -----------------------------------------------------------------------
 * Cornerstone blog slugs — evergreen guides that target head terms
 * ---------------------------------------------------------------------*/
const CORNERSTONE_SLUGS = new Set([
  "how-to-sell-your-car-for-cash-brisbane",
  "how-to-sell-a-car-without-rego-brisbane",
  "how-to-cancel-car-rego-qld",
  "how-to-transfer-car-ownership-qld",
  "wovr-written-off-vehicle-register-qld-guide",
  "scrap-metal-prices-brisbane-2026",
]);

/* -----------------------------------------------------------------------
 * Builders — each returns a MetadataRoute.Sitemap for its content type.
 * Exported for unit tests.
 * ---------------------------------------------------------------------*/

export function buildPagesSitemap(): MetadataRoute.Sitemap {
  const latestBlogDate = indexableBlogPosts.reduce(
    (latest, post) => {
      const stamp = post.updatedAt || post.date;
      return stamp > latest ? stamp : latest;
    },
    "2025-01-01",
  );

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: SITE_URL,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "weekly",
      priority: 1.0,
      images: HERO_IMAGE,
    },
    {
      url: `${SITE_URL}/about`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/faq`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/locations`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "weekly",
      priority: 0.9,
      images: HERO_IMAGE,
    },
    {
      url: `${SITE_URL}/blog`,
      lastModified: latestBlogDate,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/privacy`,
      lastModified: monthYearToISO(LEGAL_DATES.privacyLastUpdated),
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${SITE_URL}/terms`,
      lastModified: monthYearToISO(LEGAL_DATES.termsLastUpdated),
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${SITE_URL}/accessibility`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${SITE_URL}/site-map`,
      lastModified: CONTENT_DEPLOY_DATE,
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${SITE_URL}/author/sam-williams`,
      lastModified: latestBlogDate,
      changeFrequency: "monthly",
      priority: 0.4,
    },
  ];

  const servicePages: MetadataRoute.Sitemap = services.map((s) => ({
    url: `${SITE_URL}/${s.slug}`,
    lastModified: CONTENT_DEPLOY_DATE,
    changeFrequency: "monthly" as const,
    priority: PRIMARY_SERVICE_SLUGS.has(s.slug) ? 0.9 : 0.8,
    images: HERO_IMAGE,
  }));

  return [...staticPages, ...servicePages];
}

export function buildLocationsSitemap(): MetadataRoute.Sitemap {
  return suburbs.map((s) => ({
    url: `${SITE_URL}/locations/${s.slug}`,
    lastModified: CONTENT_DEPLOY_DATE,
    changeFrequency: "monthly" as const,
    priority: 0.7,
    images: HERO_IMAGE,
  }));
}

export function buildBlogSitemap(): MetadataRoute.Sitemap {
  const blogPages: MetadataRoute.Sitemap = indexableBlogPosts.map((p) => {
    const modified = p.updatedAt || p.date;
    return {
      url: `${SITE_URL}/blog/${p.slug}`,
      lastModified: modified,
      changeFrequency: changeFreqByAge(modified),
      priority: CORNERSTONE_SLUGS.has(p.slug) ? 0.8 : 0.6,
      images: HERO_IMAGE,
    };
  });

  const categoryPages: MetadataRoute.Sitemap = Object.keys(categoryMap).map(
    (slug) => {
      const postsInCategory = getPostsByCategory(slug);
      const latestInCategory = postsInCategory.reduce(
        (latest, p) => {
          const stamp = p.updatedAt || p.date;
          return stamp > latest ? stamp : latest;
        },
        "2025-01-01",
      );
      return {
        url: `${SITE_URL}/blog/category/${slug}`,
        lastModified: latestInCategory,
        changeFrequency: "monthly" as const,
        priority: 0.5,
      };
    },
  );

  return [...blogPages, ...categoryPages];
}

/* -----------------------------------------------------------------------
 * Main sitemap handler — Next.js calls this with { id } from the index.
 * ---------------------------------------------------------------------*/
export default function sitemap({ id }: { id: number }): MetadataRoute.Sitemap {
  switch (id) {
    case SITEMAP_PAGES:
      return buildPagesSitemap();
    case SITEMAP_LOCATIONS:
      return buildLocationsSitemap();
    case SITEMAP_BLOG:
      return buildBlogSitemap();
    default:
      return [];
  }
}
