// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/header-redesign/BoldNav.tsx": () => import("../components/mockups/header-redesign/BoldNav.tsx"),
  "./components/mockups/header-redesign/Current.tsx": () => import("../components/mockups/header-redesign/Current.tsx"),
  "./components/mockups/header-redesign/SplitBar.tsx": () => import("../components/mockups/header-redesign/SplitBar.tsx")
};
